
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'FOR NUMBER WORDfor_loop : FOR WORD WORD WORDexpression : WORDexpression : NUMBER'
    
_lr_action_items = {'FOR':([0,],[2,]),'$end':([1,5,],[0,-1,]),'WORD':([2,3,4,],[3,4,5,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'for_loop':([0,],[1,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> for_loop","S'",1,None,None,None),
  ('for_loop -> FOR WORD WORD WORD','for_loop',4,'p_for_loop','parser.py',6),
  ('expression -> WORD','expression',1,'p_expression_word','parser.py',10),
  ('expression -> NUMBER','expression',1,'p_expression_number','parser.py',14),
]
