
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'ID INT LBRACE LPAREN MAIN RBRACE RPAREN SEMICOLONprogram : INT MAIN LPAREN RPAREN LBRACE declarations RBRACEdeclarations : declaration SEMICOLON\n                    | declaration SEMICOLON declarationsdeclaration : INT ID'
    
_lr_action_items = {'INT':([0,6,12,],[2,7,7,]),'$end':([1,11,],[0,-1,]),'MAIN':([2,],[3,]),'LPAREN':([3,],[4,]),'RPAREN':([4,],[5,]),'LBRACE':([5,],[6,]),'ID':([7,],[10,]),'RBRACE':([8,12,13,],[11,-2,-3,]),'SEMICOLON':([9,10,],[12,-4,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'program':([0,],[1,]),'declarations':([6,12,],[8,13,]),'declaration':([6,12,],[9,9,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> program","S'",1,None,None,None),
  ('program -> INT MAIN LPAREN RPAREN LBRACE declarations RBRACE','program',7,'p_program','parser.py',9),
  ('declarations -> declaration SEMICOLON','declarations',2,'p_declarations','parser.py',13),
  ('declarations -> declaration SEMICOLON declarations','declarations',3,'p_declarations','parser.py',14),
  ('declaration -> INT ID','declaration',2,'p_declaration','parser.py',21),
]
